name: Build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        lua-version: ["5.1", "5.2", "5.3", "5.4", "luajit"]
        include:
          - lua-incdir: "./.lua/include"
          - lua-version: "luajit"
            lua-incdir: "./.lua/include/luajit-2.1"

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Lua ${{ matrix.lua-version }}
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.lua-version }}

    - name: Build lua-periphery
      run: make clean all LUA_INCDIR=${{ matrix.lua-incdir }}

    - name: Load lua-periphery
      run: lua -v -e "print(require('periphery'))"
